name: Commit and Push Changes

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Verify ImageMagick Installation
      - name: Verify ImageMagick Installation
        run: |
          magick --version
        shell: bash

      # Step 3: Run the Shell Script for Image Conversion
      - name: Run Shell Script to Create Sketch
        run: |
          chmod +x create_sketch.sh
          ./create_sketch.sh
        shell: bash

      # Step 4: Configure Git using secrets for user name and email
      - name: Set up Git with Secrets
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      # Step 5: Add all created/modified files
      - name: Add Changes
        run: |
          git add .

      # Step 6: Commit the changes to the master branch
      - name: Commit Changes
        run: |
          git commit -m "Automated commit: Add sketch output"

      # Step 7: Push to the master branch
        run: |
          git push origin master
