name: Commit and Push Changes

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      # Step 3: Verify Python Version
      - name: Verify Python Version
        run: |
          python3 --version

      # Step 4: Attempt to Install Dependencies
      - name: Attempt to Install Turtle
        run: |
          python3 -m pip install --upgrade pip
          pip install turtle==0.0.1 --use-deprecated=backtrack-on-build-failures || echo "Skipping turtle installation"

      # Step 5: Install SketchPy and Dependencies
      - name: Install SketchPy and Dependencies
        run: |
          pip install sketchpy==0.0.27

      # Step 6: Run the Python Script
      - name: Run SketchPy Script
        run: |
          python3 test_sketchpy.py

      # Step 7: Configure Git using secrets for user name and email
      - name: Set up Git with Secrets
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      # Step 8: Add all created/modified files
      - name: Add Changes
        run: |
          git add .

      # Step 9: Commit the changes to the master branch
      - name: Commit Changes
        run: |
          git commit -m "Automated commit: Add sketch output"

      # Step 10: Push to the master branch
      - name: Push to Master Branch
        run: |
          git push origin master
