name: Run create_sketch.sh script

on:
  workflow_dispatch: # Enables manual trigger via "Run workflow" button

jobs:
  execute-shell-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Grant execution permissions for the shell script
      - name: Make create_sketch.sh executable
        run: chmod +x ./create_sketch.sh

      # Step 3: Run create_sketch.sh
      - name: Run create_sketch.sh
        run: ./create_sketch.sh
