name: Run main.sh script

on:
  workflow_dispatch: # Enables manual trigger via "Run workflow" button

jobs:
  execute-shell-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Grant execution permissions for the shell script
      - name: Make main.sh executable
        run: chmod +x ./main.sh

      # Step 3: Run main.sh
      - name: Run main.sh
        run: ./main.sh



