name: Commit and Push Changes

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      # Step 3: Verify Python Version
      - name: Verify Python Version
        run: |
          python3 --version

      # Step 4: Reinstall svgpathtools and Ensure svg.path
      - name: Install svgpathtools
        run: |
          python3 -m pip install --upgrade pip
          pip3 install svgpathtools

      # Step 5: Install SketchPy Without Dependencies
      - name: Install SketchPy Without Dependencies
        run: |
          pip3 install sketchpy==0.0.27 --no-deps

      # Step 6: Install Remaining Dependencies
      - name: Install Remaining Dependencies
        run: |
          pip3 install opencv-python tqdm Pillow wheel

      # Step 7: Run the Python Script
      - name: Run SketchPy Script
        run: |
          python3 test_sketchpy.py

      # Step 8: Configure Git using secrets for user name and email
      - name: Set up Git with Secrets
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      # Step 9: Add all created/modified files
      - name: Add Changes
        run: |
          git add .

      # Step 10: Commit the changes to the master branch
      - name: Commit Changes
        run: |
          git commit -m "Automated commit: Add sketch output"

      # Step 11: Push to the master branch
      - name: Push to Master Branch
        run: |
          git push origin master
