name: Commit and Push Changes

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Download and Install ImageMagick
      - name: Download and Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://imagemagick.org/archive/ImageMagick.tar.gz
          tar -xvzf ImageMagick.tar.gz
          cd ImageMagick-*
          ./configure
          make
          sudo make install
          sudo ldconfig /usr/local/lib
        shell: bash

      # Step 3: Verify ImageMagick Installation
      - name: Verify ImageMagick Installation
        run: |
          magick --version
        shell: bash

      # Step 4: Run the Shell Script for Image Conversion
      - name: Run Shell Script to Create Sketch
        run: |
          bash ./create_sketch.sh
        shell: bash

      # Step 5: Configure Git using secrets for user name and email
      - name: Set up Git with Secrets
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      # Step 6: Add all created/modified files
      - name: Add Changes
        run: |
          git add .

      # Step 7: Commit the changes to the master branch
      - name: Commit Changes
        run: |
          git commit -m "Automated commit: Add sketch output"

      # Step 8: Push to the master branch
      - name: Push to Master Branch
        run: |
          git push origin master
