name: Run main.sh script

on:
  workflow_dispatch: # Enables manual trigger via "Run workflow" button

jobs:
  execute-shell-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug - List Files in Repository
      - name: List Files in Repository
        run: ls -la

      # Step 3: Debug main.sh contents
      - name: Debug main.sh contents
        run: cat ./main.sh

      # Step 4: Grant execution permissions for the shell script
      - name: Make main.sh executable
        run: chmod +x ./main.sh

      # Step 5: Run main.sh
      - name: Run main.sh
        run: ./main.sh
