name: Install ImageMagick and Push Changes

on:
  workflow_dispatch: # Enables manual trigger via "Run workflow" button

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python 3.7 from Deadsnakes PPA
      - name: Install Python 3.7
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y python3.7 python3-pip python3-distutils
          python3.7 --version # Verify Python 3.7 installation

      # Step 3: Install dependencies and ImageMagick with JPEG support
      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential libjpeg-dev
          wget https://imagemagick.org/archive/ImageMagick.tar.gz
          tar -xvzf ImageMagick.tar.gz
          cd ImageMagick-*
          ./configure
          make
          sudo make install
          sudo ldconfig /usr/local/lib

      # Step 4: Install Python dependencies globally
      - name: Install Python dependencies globally
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      # Step 5: Grant execution permissions for the shell script
      - name: Make main.sh executable
        run: chmod +x ./main.sh

      # Step 6: Run main.sh
      - name: Run main.sh
        run: ./main.sh

      # Step 7: Run the Python script for unwanted elements
      - name: Run Python script
        run: python3 remove_unwanted_elements.py

      # Step 8: Configure Git using secrets for user name and email
      - name: Set up Git with Secrets
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      # Step 9: Add only specific folders to the commit
      - name: Add Changes from Specific Folders
        run: |
          git add book_compilation/
          git add converted_sketches/
          git add original_photos/

      # Step 10: Commit the changes to the master branch
      - name: Commit Changes
        run: git commit -m "Automated commit - update by main.sh"

      # Step 11: Push to the master branch
      - name: Push to Master Branch
        run: git push origin master



