name: Install ImageMagick and Push Changes

on:
  workflow_dispatch: # Enables manual trigger via "Run workflow" button

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python 3.7
      - name: Install Python 3.7
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.7 python3.7-venv python3.7-distutils
          python3.7 --version # Verify Python 3.7 installation

      # Step 3: Install dependencies and ImageMagick with JPEG support
      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential libjpeg-dev
          wget https://imagemagick.org/archive/ImageMagick.tar.gz
          tar -xvzf ImageMagick.tar.gz
          cd ImageMagick-*
          ./configure
          make
          sudo make install
          sudo ldconfig /usr/local/lib

      # Step 4: Verify ImageMagick installation and JPEG support
      - name: Verify ImageMagick Installation
        run: |
          magick --version
          magick -list format | grep -i jpeg

      # Step 5: Debug input file (optional step to verify input file existence and type)
      - name: Verify input file
        run: file ./original_photos/photo.jpg

      # Step 6: Grant execution permissions for the shell script
      - name: Make main.sh executable
        run: chmod +x ./main.sh

      # Step 7: Run main.sh with Python 3.7
      - name: Run main.sh
        run: |
          python3.7 -m venv venv  # Create virtual environment using Python 3.7
          source venv/bin/activate
          ./main.sh
          deactivate

      # Step 8: Configure Git using secrets for user name and email
      - name: Set up Git with Secrets
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      # Step 9: Add only specific folders to the commit
      - name: Add Changes from Specific Folders
        run: |
          git add book_compilation/
          git add converted_sketches/
          git add original_photos/

      # Step 10: Commit the changes to the master branch
      - name: Commit Changes
        run: git commit -m "Automated commit - update by main.sh"

      # Step 11: Push to the master branch
      - name: Push to Master Branch
        run: git push origin master


